version: '3.7'
services:
  mysql:
    ports:
      - '${MYSQL_PORT}:3306'

  php:
    volumes:
      - './apps/my-app/:/usr/src/app'

  nginx:
    volumes:
      - './apps/my-app/public/:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
